model_name_or_path: "klue/bert-base"
config_name: null
tokenizer_name: null
dataset_name: "data/train_dataset"
overwrite_cache: False
preprocessing_num_workers: null
max_seq_length: 384
pad_to_max_length: False
doc_stride: 128
max_answer_length: 30
eval_retrieval: True
num_clusters: 64
top_k_retrieval: 10
use_faiss: False